import type { ProjectSystemVariant } from "@/app/components/ProjectSystemModel";
export const experiences = [
  {
    code: "CURRENT ROLE",
    status: "IN PROGRESS",
    role: "Data Scientist Intern (Co-op)",
    company: "Delta Dental Insurance",
    logo: "logos/delta-dental.jpg",
    logoAlt: "Delta Dental logo",
    logoClass: "delta",
    period: "Jun 2025 - Present",
    summary: "Building governed GenAI analytics, document intelligence, and healthcare ML systems across the full production stack.",
    highlights: [
      "Unified 131 datasets in a governed Provider Insights AI platform and cut LLM analytics latency by 80%+.",
      "Built a vision-language invoice pipeline for handwritten and non-standard formats, eliminating hundreds of manual hours.",
      "Led self-supervised transformer learning across 3M+ claims, improving recall 40%+ over baselines.",
      "Engineered partition-aware Oracle SQL and Dataiku pipelines for multimillion-row actuarial workloads.",
      "Designed backup, recovery, and version-controlled ML lifecycle infrastructure with MLflow.",
    ],
    reward: "+4 major systems",
    tags: ["GenAI", "Dataiku", "Snowflake", "Azure OpenAI", "PyTorch", "MLflow"],
  },
  {
    code: "ROLE 04",
    status: "COMPLETE",
    role: "Data Scientist",
    company: "Ernst & Young (EY)",
    logo: "logos/ey.svg",
    logoAlt: "EY logo",
    logoClass: "ey",
    period: "Jan 2023 - Jun 2024",
    summary: "Advised Fortune 500 teams on cloud ML architecture, experimentation, data modernization, and production inference.",
    highlights: [
      "Cut ETL latency from 4+ hours to under 30 minutes across 5M+ daily records.",
      "Reduced retraining time 30% and improved inference accuracy 15% through AWS SageMaker modernization.",
      "Designed A/B tests and uplift models that drove a 30% revenue KPI lift.",
      "Deployed multi-region FastAPI services with zero-downtime rollouts and 25% faster delivery.",
    ],
    reward: "+30% revenue KPI",
    tags: ["AWS", "SageMaker", "Airflow", "FastAPI", "Causal ML", "Docker"],
  },
  {
    code: "ROLE 03",
    status: "COMPLETE",
    role: "Data Science Intern",
    company: "Ernst & Young (EY)",
    logo: "logos/ey.svg",
    logoAlt: "EY logo",
    logoClass: "ey",
    period: "Jun 2022 - Aug 2022",
    summary: "Built cross-validated models and controlled experiments across 10+ client engagements.",
    highlights: ["Improved submission rates 20% and decision quality 25% for Operations and Marketing teams."],
    reward: "+10 engagements",
    tags: ["Experimentation", "Regression", "Uplift Modeling"],
  },
  {
    code: "ROLE 02",
    status: "COMPLETE",
    role: "Software Engineering Intern",
    company: "Exodrone Systems",
    logo: "logos/exodrone-systems.png",
    logoAlt: "Exodrone Systems logo",
    logoClass: "exodrone",
    period: "Dec 2021 - Jun 2022",
    summary: "Extended Mission Planner across frontend and backend systems using C#, .NET, and REST APIs.",
    highlights: ["Improved operator efficiency 35% and cut mission configuration load time 60%."],
    reward: "+60% load speed",
    tags: ["C#", ".NET", "REST APIs"],
  },
  {
    code: "ROLE 01",
    status: "COMPLETE",
    role: "Data Science Intern",
    company: "NIIT Technologies",
    logo: "logos/niit-technologies.svg",
    logoAlt: "NIIT Technologies logo",
    logoClass: "niit",
    period: "Jun 2021 - Dec 2021",
    summary: "Developed and deployed a production CNN with real-time inference and automated drift monitoring.",
    highlights: ["Achieved 95%+ accuracy with sub-100ms inference latency."],
    reward: "+95% accuracy",
    tags: ["PyTorch", "CNN", "Model Monitoring"],
  },
];

export const projects = [
  {
    id: "agentguard",
    artifact: "guard" as ProjectSystemVariant,
    name: "AgentGuard",
    title: "Security gateway for AI agents",
    description: "A runtime security layer that intercepts MCP tool calls, enforces deterministic policy, redacts secrets, pauses risky actions for human approval, and writes a tamper-evident audit trail.",
    outcome: "Unsafe tool execution blocked before it reaches production systems.",
    stats: ["4 attack fixtures", "4 agent runtimes", "Tamper-evident audit"],
    tools: ["MCP", "OpenAI Agents", "LangGraph", "PydanticAI", "Qdrant"],
    href: "https://github.com/vaasu202/agentguard",
    image: "projects/agentguard-demo.png",
    imageAlt: "AgentGuard security gateway interface",
  },
  {
    id: "longview",
    artifact: "forecast" as ProjectSystemVariant,
    name: "Longview",
    title: "Demand and capacity forecasting",
    description: "A multi-segment forecasting system combining Temporal Fusion Transformer and SARIMAX across more than 40 contract segments, validated with walk-forward testing.",
    outcome: "$3.5M in annual risk reduction.",
    stats: ["22% RMSE improvement", "18% MAPE improvement", "40+ segments"],
    tools: ["TFT", "SARIMAX", "Time series", "Python"],
    href: null,
    image: "projects/demand-capacity-forecast.png",
    imageAlt: "Demand and capacity forecast visualization",
  },
  {
    id: "nexus",
    artifact: "agents" as ProjectSystemVariant,
    name: "Nexus",
    title: "Multi-agent retrieval platform",
    description: "A deterministic operational intelligence system using LangGraph, GPT-4.1, ChromaDB hybrid retrieval, structured tool use, and Pydantic validation.",
    outcome: "Grounded answers from complex operational knowledge.",
    stats: ["Hybrid retrieval", "Structured calling", "Natural-language Q&A"],
    tools: ["LangGraph", "GPT-4.1", "ChromaDB", "Streamlit"],
    href: "https://github.com/vaasu202/Agentic-RAG-Postmortem-Reporting",
    image: "projects/multi-agent-rag.png",
    imageAlt: "Nexus multi-agent retrieval application",
  },
  {
    id: "ecg-anomaly-detection",
    artifact: "ecg" as ProjectSystemVariant,
    name: "ECG Anomaly Detection",
    title: "Published clinical ML research",
    description: "A peer-reviewed interpretable autoencoder framework for anomaly detection and pattern recognition on clinical ECG signals.",
    outcome: "Clinical signals translated into interpretable anomaly patterns.",
    stats: ["Peer reviewed", "Clinical ECG", "Interpretable ML"],
    tools: ["Autoencoders", "PyTorch", "Clinical ML"],
    href: "https://ieeexplore.ieee.org/document/10372979",
    image: "projects/ecg-anomaly-detection.png",
    imageAlt: "ECG anomaly detection research visualization",
  },
];

export const skillGroups = [
  { icon: "01", label: "Cloud Infrastructure", focus: "Cloud and deployment", skills: ["AWS S3", "SageMaker", "Athena", "Bedrock", "Snowflake", "Docker", "Kubernetes"] },
  { icon: "02", label: "Data Engineering", focus: "Pipelines and platforms", skills: ["ETL / ELT", "Airflow", "Spark", "Dataiku", "Oracle SQL", "PostgreSQL", "Optimization"] },
  { icon: "03", label: "ML Systems", focus: "Training and serving", skills: ["PyTorch Lightning", "Transformers", "MLflow", "FastAPI", "Optuna", "CI/CD"] },
  { icon: "04", label: "GenAI Systems", focus: "Agents and retrieval", skills: ["LangGraph", "LangChain", "RAG", "Prompt Engineering", "Pydantic", "Azure OpenAI"] },
  { icon: "05", label: "Evaluation", focus: "Quality and observability", skills: ["LLM-as-a-Judge", "Ragas", "LangSmith", "TruLens", "MLflow Evaluate", "Observability"] },
  { icon: "06", label: "Decision Science", focus: "Forecasting and experimentation", skills: ["Forecasting", "A/B Testing", "Uplift Modeling", "Causal Inference", "Predictive Analytics"] },
];


